version: '3'
services:
  study-weeks:
    image: dsek/study-week-feed:0.1
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./main.dev.env
      - ./main.prod.env
    restart: unless-stopped
  db:
    image: mysql/mysql-server:8.0
    ports:
      - "3306"
    env_file:
      - ./db.dev.env
      - ./db.prod.env
    volumes:
      - "./database_init/:/docker-entrypoint-initdb.d/:ro"
