version: '3'
services:
  study-weeks:
    image: dsek/study-week-feed:0.1
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      JDBC_URL: jdbc:mysql://db/studyweeks
    restart: unless-stopped
  db:
    image: mysql/mysql-server:8.0
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: studyweeks
      MYSQL_USER: testuser
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - "./database_init/:/docker-entrypoint-initdb.d/:ro"
